-- liquibase formatted sql

-- changeset renasafetysea:1
CREATE TABLE IF NOT EXISTS comments
(
    id         BIGSERIAL PRIMARY KEY,
    ads_id     BIGINT,
    author_id  BIGINT,
    created_at TIMESTAMP,
    text       varchar(200)
);
CREATE TABLE IF NOT EXISTS users
(
    id         BIGSERIAL PRIMARY KEY,
    username varchar(50)  not null,
    password varchar(120) not null,
    first_name   varchar(30),
    last_name    varchar(40),
    phone        varchar(12),
    image     BIGINT,
    reg_date        VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS ads
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT,
    title       VARCHAR(255),
    price       INTEGER NOT NULL,
    description VARCHAR(255)

);

CREATE TABLE IF NOT EXISTS image
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    path   text,
    ads_id BIGINT,
    image bytea,
    mediaType VARCHAR


);





